FROM node:20-alpine

# On s'assure que le dossier appartient à 'node'
WORKDIR /app
RUN chown -R node:node /app

# On bascule sur l'utilisateur node avant d'installer les dépendances
USER node

COPY --chown=node:node package*.json ./
RUN npm install

COPY --chown=node:node . .

RUN chown -R node:node /app

# La génération se fera avec les permissions de l'utilisateur node
RUN npx prisma generate

RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["sh", "./entrypoint.sh"]
CMD ["npm", "run", "start:dev"]